import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {context,loadPortal,mutate} from '../src/portal.ts';
import {demoSeed} from '../src/seed.ts';
function fixture(){const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');sqlite.exec(readFileSync(new URL('../prisma/migrations/001_family/migration.sql',import.meta.url),'utf8'));const db={query:async(sql:string,args:SQLInputValue[]=[])=>sqlite.prepare(sql).all(...args)};for(const s of demoSeed())sqlite.prepare(s.sql).run(...s.args);return{db,close:()=>sqlite.close()};}
test('role and child scope excludes sibling, invoices and parent messages from student',async()=>{const f=fixture();try{assert.throws(()=>context('student','jiwoo'));assert.throws(()=>context('teacher','haneul'));assert.throws(()=>context('parent',"' OR 1=1"));const parent=context('parent','haneul');await mutate(f.db,parent,{action:'message',body:'parent private demo conversation'});const student=await loadPortal(f.db,context('student','haneul'));assert.equal(student.profiles.length,1);assert.equal(student.invoices.length,0);assert.ok(student.sessions.every(s=>s.studentId==='haneul'));assert.ok(!student.messages.some(m=>m.body==='parent private demo conversation'));const sibling=await loadPortal(f.db,context('parent','jiwoo'));assert.equal(sibling.profile.name,'김지우');assert.ok(sibling.sessions.every(s=>s.studentId==='jiwoo'));}finally{f.close();}});
test('writes are scoped, validated and persist; payment is a guarded demo transition',async()=>{const f=fixture();try{const ctx=context('parent','haneul');await assert.rejects(mutate(f.db,ctx,{action:'pay',id:'jiwoo-invoice'}));await assert.rejects(mutate(f.db,context('student','haneul'),{action:'pay',id:'haneul-invoice'}));await mutate(f.db,ctx,{action:'pay',id:'haneul-invoice'});await assert.rejects(mutate(f.db,ctx,{action:'pay',id:'haneul-invoice'}));assert.equal((await loadPortal(f.db,ctx)).invoices[0].status,'demo-paid');await assert.rejects(mutate(f.db,ctx,{action:'message',body:' '}));await assert.rejects(mutate(f.db,ctx,{action:'message',body:'x'.repeat(1001)}));await mutate(f.db,ctx,{action:'message',body:'저장되는 쪽지'});assert.ok((await loadPortal(f.db,ctx)).messages.some(m=>m.body==='저장되는 쪽지'));await assert.rejects(mutate(f.db,ctx,{action:'intention',id:'haneul-session-0',choice:'absent',reason:'과거'}));await assert.rejects(mutate(f.db,ctx,{action:'intention',id:'jiwoo-session-2',choice:'absent',reason:'다른 학생'}));await assert.rejects(mutate(f.db,ctx,{action:'intention',id:'haneul-session-2',choice:'absent',reason:''}));await mutate(f.db,ctx,{action:'intention',id:'haneul-session-2',choice:'absent',reason:'체험 일정'});assert.equal((await loadPortal(f.db,ctx)).sessions.find(s=>s.id==='haneul-session-2')?.intention,'absent');}finally{f.close();}});
test('read receipts and one updatable vote per role remain separate',async()=>{const f=fixture();try{const ctx=context('parent','haneul');await assert.rejects(mutate(f.db,ctx,{action:'read',id:'jiwoo-notice'}));await assert.rejects(mutate(f.db,ctx,{action:'vote',id:'haneul-notice',choice:'attend'}));await assert.rejects(mutate(f.db,ctx,{action:'vote',id:'haneul-poll',choice:'invalid'}));await mutate(f.db,ctx,{action:'vote',id:'haneul-poll',choice:'attend'});await mutate(f.db,ctx,{action:'vote',id:'haneul-poll',choice:'decline'});const parent=await loadPortal(f.db,ctx);assert.equal(parent.notices.find(n=>n.id==='haneul-poll')?.choice,'decline');assert.equal(parent.notices.find(n=>n.id==='haneul-poll')?.isRead,1);const student=await loadPortal(f.db,context('student','haneul'));assert.equal(student.notices.find(n=>n.id==='haneul-poll')?.choice,null);assert.equal(student.notices.find(n=>n.id==='haneul-poll')?.isRead,0);}finally{f.close();}});
