'use client';
import {useState} from 'react';
import Image from 'next/image';
import {Button} from './ui/button';
import {Label} from './ui/label';
import {Textarea} from './ui/textarea';
import {Badge} from './ui/badge';
import type {Notice,PortalData,Comment} from '../src/model';
import type {Act} from './payments-panel';
export const mediaAssets:Record<string,{src:string;label:string}>={reading:{src:'/family-reading.svg',label:'함께 읽는 시간'},art:{src:'/family-art.svg',label:'색으로 표현하는 시간'},schedule:{src:'/family-schedule.svg',label:'수업 준비 안내'}};
export function NoticeDetail({notice,data,act,busy}:{notice:Notice;data:PortalData;act:Act;busy:boolean}){
 const [reply,setReply]=useState<string|null>(null),[editing,setEditing]=useState<string|null>(null),[draft,setDraft]=useState('');
 const comments=data.comments.filter(c=>c.noticeId===notice.id);
 const renderComment=(c:Comment)=><article className={'comment '+(c.parentId?'reply':'')} key={c.id}><div className="comment-meta"><Badge variant="outline">{c.role==='parent'?'학부모':'학생'}</Badge><time>{new Date(c.createdAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</time>{c.updatedAt!==c.createdAt&&!c.deleted?<span>수정됨</span>:null}</div>{editing===c.id?<form onSubmit={async e=>{e.preventDefault();if(await act({action:'editComment',id:c.id,body:draft},'댓글을 수정했어요.',false))setEditing(null);}}><Label htmlFor="edit-comment">댓글 수정 내용</Label><Textarea id="edit-comment" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={1000} required/><div className="inline-badges"><Button disabled={busy} type="submit">수정 저장</Button><Button disabled={busy} variant="ghost" type="button" onClick={()=>setEditing(null)}>취소</Button></div></form>:<p className="comment-body">{c.deleted?'삭제된 댓글이에요.':c.body}</p>}{!c.deleted&&!editing?<div className="inline-badges">{!c.parentId?<Button size="sm" variant="ghost" disabled={busy} onClick={()=>setReply(c.id)}>답글</Button>:null}{c.role===data.context.role?<><Button size="sm" variant="ghost" disabled={busy} onClick={()=>{setEditing(c.id);setDraft(c.body);}}>수정</Button><Button size="sm" variant="ghost" disabled={busy} onClick={()=>act({action:'deleteComment',id:c.id},'댓글을 삭제했어요.',false)}>삭제</Button></>:null}</div>:null}</article>;
 return <><p className="notice-body">{notice.body}</p><div className="album-grid">{data.media.filter(m=>m.noticeId===notice.id&&mediaAssets[m.asset]).map(m=><figure key={m.id}><Image src={mediaAssets[m.asset].src} alt={m.caption} width={600} height={400} className="album-image"/><figcaption className="muted">{m.caption}</figcaption><Button asChild variant="outline" size="sm"><a href={mediaAssets[m.asset].src} download>그림 다운로드</a></Button></figure>)}</div>{notice.poll?<div><p className="muted">{notice.choice?'현재 응답: '+(notice.choice==='attend'?'참석':'불참'):'참석 여부를 알려주세요.'}</p><div className="vote-actions"><Button disabled={busy} onClick={()=>act({action:'vote',id:notice.id,choice:'attend'},'참석으로 응답했어요.')}>참석할게요</Button><Button variant="outline" disabled={busy} onClick={()=>act({action:'vote',id:notice.id,choice:'decline'},'불참으로 응답했어요.')}>다음에 함께할게요</Button></div></div>:null}<Button variant="outline" disabled={busy} onClick={()=>act({action:'read',id:notice.id},'공지를 확인했어요.')}>확인했어요</Button><section aria-label="공지 댓글"><h2>댓글 {comments.filter(c=>!c.deleted).length}</h2><p className="muted">다른 방문자와 공유하는 가상 역할의 댓글이에요. 개인정보는 적지 마세요.</p>{comments.filter(c=>!c.parentId).map(c=><div key={c.id}>{renderComment(c)}{comments.filter(r=>r.parentId===c.id).map(renderComment)}</div>)}{comments.filter(c=>c.parentId&&!comments.some(p=>p.id===c.parentId)).map(renderComment)}<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const values=new FormData(form);if(await act({action:'comment',id:notice.id,parentId:reply,body:values.get('comment')},'댓글을 저장했어요.',false)){form.reset();setReply(null);}}}>{reply?<div className="inline-badges"><Badge>답글 작성 중</Badge><Button type="button" size="sm" variant="ghost" onClick={()=>setReply(null)}>답글 취소</Button></div>:null}<Label htmlFor="comment-body">{reply?'답글 내용':'댓글 내용'}</Label><Textarea id="comment-body" name="comment" maxLength={1000} required/><Button className="send-button" disabled={busy} type="submit">{reply?'답글 저장':'댓글 저장'}</Button></form></section></>;
}
